knutd_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', include('settlement.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

settlement/urls.py
from django.urls import path
from . import views

app_name = 'settlement'
urlpatterns = [
    # path('<int:hostel_number>/', views.hostel, name='hostel'),
    # path('<int:hostel_number/floor_number>', views.floor, name='floor'),
    path('add_student/', views.forms, name='add_student'),
    path('', views.dormitories, name='dormitories'),
    path('hostel/seven/1/', views.Hostel_seven.one, name='one'),
    path('hostel/seven/2/', views.Hostel_seven.two, name='two'),
    path('hostel/seven/3/', views.Hostel_seven.three, name='three'),
    path('hostel/seven/4/', views.Hostel_seven.four, name='four'),
    path('hostel/seven/5/', views.Hostel_seven.five, name='five'),
    path('hostel/seven/6/', views.Hostel_seven.six, name='six'),
    path('hostel/seven/7/', views.Hostel_seven.seven, name='seven'),


]

templates/swttlement/dormitories.html
{% extends 'base.html' %}

{% block name %}Головна{% endblock %}

{% block content %}
    {% for a in hostel %}
        <div class="wrapper" data-astro-cid-ili6pcsu>
            <div class="card mb-[20px]" data-astro-cid-dohjnao5>
                <div class="flex justify-between" data-astro-cid-dohjnao5><h2 class="number h2 mb-[20px]"
                                                                              data-astro-cid-dohjnao5>Гуртожиток
                    №{{ a.hostel_number }}</h2><a
                        href="/" class="card_btn" data-astro-cid-dohjnao5>Обрати</a></div>
                <div class="flex" data-astro-cid-dohjnao5>
                    <div class="mr-[45px]" data-astro-cid-dohjnao5><h4 class="h4" data-astro-cid-dohjnao5>Хто проживає в
                        гуртожитку:</h4>
                        <p class="description mt-[18px] max-h-[100px] max-w-[241px]"
                           data-astro-cid-dohjnao5>{{ a.residents }}</p></div>
                    <div data-astro-cid-dohjnao5><h4 class="h4" data-astro-cid-dohjnao5>Адреса гуртожитку та
                        контакти:</h4>
                        <div class="info" data-astro-cid-dohjnao5><p class="address mt-[18px]"
                                                                     data-astro-cid-dohjnao5>{{ a.address }}</p>
                            <p class="phone mt-[20px]" data-astro-cid-dohjnao5>{{ a.mobile_number }}</p></div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/swttlement/form.html
{% extends 'base.html' %}

{% block name %}Форма для студента{% endblock %}

    {% block content %}
        <h1>Форма для студента</h1>
        <form method="post" id="student-form">
        {% csrf_token %}
        {% for f in form %}
            {{ form }}

        {% endfor %}
            <input type="submit" value="Зберегти">
        </form>

    {% endblock %}

templates/swttlement/hostel.html
{% extends 'base.html' %}
{% load static %}
{% block name %}Гуртожиток 7{% endblock %}

{% block content %}
    <div class="wrapper" data-astro-cid-j7pv25f6>
        <div class="mt-[40px] flex justify-between" data-astro-cid-j7pv25f6>
            <ul class="floors" data-astro-cid-j7pv25f6>
                <li class="active" data-astro-cid-j7pv25f6>
                    <a id="floor_1" href="{% url 'settlement:one' %}" data-astro-cid-j7pv25f6>1 поверх</a>
                </li>
                <li data-astro-cid-j7pv25f6>
                    <a id="floor_2" href="{% url 'settlement:two' %}" data-astro-cid-j7pv25f6>2 поверх</a>
                </li>
                <li data-astro-cid-j7pv25f6>
                    <a id="floor_3" href="{% url 'settlement:three' %}" data-astro-cid-j7pv25f6>3 поверх</a>
                </li>
                <li data-astro-cid-j7pv25f6>
                    <a id="floor_4" href="{% url 'settlement:four' %} " data-astro-cid-j7pv25f6>4 поверх</a>
                </li>
                <li data-astro-cid-j7pv25f6>
                    <a id="floor_5" href="{% url 'settlement:five' %}" data-astro-cid-j7pv25f6>5 поверх</a>
                </li>
                <li data-astro-cid-j7pv25f6>
                    <a id="floor_6" href="{% url 'settlement:six' %}" data-astro-cid-j7pv25f6>6 поверх</a>
                </li>
                <li data-astro-cid-j7pv25f6>
                    <a id="floor_7" href="{% url 'settlement:seven' %}" data-astro-cid-j7pv25f6>7 поверх</a>
                </li>
            </ul>
            <div class="dormitory_number" data-astro-cid-j7pv25f6>Гуртожиток&nbsp№7</div>
        </div>
    </div>
    <div class="flex-col items-center" data-astro-cid-j7pv25f6>
        <div class="mt-[30px]" data-astro-cid-j7pv25f6>
            <div class="flex justify-center" data-astro-cid-j7pv25f6><p class="cell inline-block"
                                                                        data-astro-cid-j7pv25f6>1 клітка</p></div>
            <div class="flex justify-center" data-astro-cid-j7pv25f6>{% block bloc_one %}{% endblock %}</div>
        </div>
        <div class="mt-[30px]" data-astro-cid-j7pv25f6>
            <div class="flex justify-center" data-astro-cid-j7pv25f6><p class="cell inline-block"
                                                                        data-astro-cid-j7pv25f6>2 клітка</p></div>
            <div class="flex justify-center" data-astro-cid-j7pv25f6>{% block bloc_two %}{% endblock %}</div>
        </div>
        <div class="mt-[30px]" data-astro-cid-j7pv25f6>
            <div class="flex justify-center" data-astro-cid-j7pv25f6><p class="cell inline-block"
                                                                        data-astro-cid-j7pv25f6>3 клітка</p></div>
            <div class="flex justify-center" data-astro-cid-j7pv25f6>{% block bloc_three %}{% endblock %}</div>
        </div>
    </div>
    <!---{% for a in s %}
            {% if a.sex == 'Ч' %}
                <img class="" alt="cell" src="{% static 'img/Group 266.svg' %}">
            {% elif a.sex == 'Ж' %}
                <img class="" alt="cell" src="{% static 'img/Group 205.svg' %}">
            {% else %}
                <img class="" alt="cell" src="{% static 'img/Group 203.svg' %}">
            {% endif %}

        {% endfor %}--->

    <div class="info h-[100px] w-[100%] rounded-[20px] mt-[40px] bg-white flex items-center"
         data-astro-cid-j7pv25f6>
        <div class="w-[1250px] h-[102px] pl-7 pr-[472px] py-[29px] bg-white rounded-[20px] justify-start items-start gap-[30px] inline-flex"
             data-astro-cid-j7pv25f6>
            <div class="w-[230px] self-stretch p-2.5 bg-violet-50 rounded-[5px] flex-col justify-center items-start gap-2.5 inline-flex"
                 data-astro-cid-j7pv25f6>
                <div class="justify-start items-center inline-flex" data-astro-cid-j7pv25f6>
                    <div class="w-6 h-6 bg-zinc-200 rounded-[5px]" data-astro-cid-j7pv25f6></div>
                    <div class="info__item" data-astro-cid-j7pv25f6>Місце зайняте</div>
                    </div>
                </div>
                <div class="self-stretch p-2.5 bg-violet-50 rounded-[5px] justify-start items-center inline-flex"
                     data-astro-cid-j7pv25f6>
                    <div class="w-6 h-6 bg-indigo-600 rounded-[5px]" data-astro-cid-j7pv25f6></div>
                    <div class="info__item" data-astro-cid-j7pv25f6>Місце вільне для хлопця</div>
                </div>
                <div class="self-stretch p-2.5 bg-violet-50 rounded-[5px] justify-center items-center inline-flex"
                     data-astro-cid-j7pv25f6>
                    <div class="w-6 h-6 bg-rose-500 rounded-[5px]" data-astro-cid-j7pv25f6></div>
                    <div class="info__item" data-astro-cid-j7pv25f6>Місце вільне для дівчини</div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}