knutd_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', include('settlement.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

settlement/urls.py
from django.urls import path
from . import views

app_name = 'settlement'
urlpatterns = [
    # path('<int:hostel_number>/', views.hostel, name='hostel'),
    # path('<int:hostel_number/floor_number>', views.floor, name='floor'),
    path('add_student/', views.forms, name='add_student'),
    path('', views.dormitories, name='dormitories'),
    path('hostel/seven/1/', views.Hostel_seven.one, name='one'),
    path('hostel/seven/2/', views.Hostel_seven.two, name='two'),
    path('hostel/seven/3/', views.Hostel_seven.three, name='three'),
    path('hostel/seven/4/', views.Hostel_seven.four, name='four'),
    path('hostel/seven/5/', views.Hostel_seven.five, name='five'),
    path('hostel/seven/6/', views.Hostel_seven.six, name='six'),
    path('hostel/seven/7/', views.Hostel_seven.seven, name='seven'),


]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <meta name="generator" content="Astro v3.1.4">
    <title>{% block name %}Settlement | Knutd{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/index.css' %}"/>
</head>
<body>
<header class="header" data-astro-cid-3ef6ksr2>
    <div class="header_wrapper" data-astro-cid-3ef6ksr2>
        <div class="header_logo" data-astro-cid-3ef6ksr2></div>
        <div class="nav" data-astro-cid-3ef6ksr2><a href="{% url 'settlement:dormitories' %}" class="nav-item active"
                                                    data-astro-cid-3ef6ksr2>Головна</a><a
                href="{% url 'settlement:one' %}" class="nav-item" data-astro-cid-3ef6ksr2>Обрати кімнату</a><a
                href="{% url 'settlement:add_student' %}" class="nav-item"
                data-astro-cid-3ef6ksr2>Заповнення документів</a></div>
    </div>
</header>
{% block content %}

{% endblock %}
<footer class="footer" data-astro-cid-sz7xmlte>
    <div class="footer_wrapper" data-astro-cid-sz7xmlte>
        <div data-astro-cid-sz7xmlte>
            <div class="footer_logo" data-astro-cid-sz7xmlte></div>
            <ul class="footer_nav mt-[30px]" data-astro-cid-sz7xmlte>
                <li class="nav-item" data-astro-cid-sz7xmlte><a href="{% url 'settlement:dormitories' %}" data-astro-cid-sz7xmlte>Головна</a></li>
                <li class="nav-item" data-astro-cid-sz7xmlte><a href="{% url 'settlement:one' %}" data-astro-cid-sz7xmlte>Обрати кімнату</a></li>
                <li class="nav-item" data-astro-cid-sz7xmlte><a href="{% url 'settlement:add_student' %}" data-astro-cid-sz7xmlte>Заповнення документів</a></li>
            </ul>
        </div>
        <div data-astro-cid-sz7xmlte><h2 class="title" data-astro-cid-sz7xmlte>Контакти</h2>
            <p class="number" data-astro-cid-sz7xmlte>+3546456468498</p>
            <p class="number" data-astro-cid-sz7xmlte>+3546456468498</p></div>
    </div>
</footer>
</body>
</html>